version: "3.7"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /media/Storage/mqtt/config:/mosquitto/config:rw
      - /media/Storage/mqtt/data:/mosquitto/data:rw
      - /media/Stroage/mqtt/logs:/mosquitto/log:rw
    restart: unless-stopped
  mqtt-database:
    image: timescale/timescaledb:latest-pg16-oss
    container_name: mqtt-database
    restart: unless-stopped
    volumes:
      - /media/Storage/mqtt/tsdb/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
  mqtt-consumer:
    build:
      context: ./consumer/
      dockerfile: Dockerfile
    container_name: mqtt-consumer
    restart: unless-stopped
    depends_on:
      - mqtt-database
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
