version: "3.7"
name: mqtt-broker
services:
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /media/Storage/mqtt/config:/mosquitto/config:rw
      - /media/Storage/mqtt/data:/mosquitto/data:rw
      - /media/Stroage/mqtt/logs:/mosquitto/log:rw
    restart: unless-stopped
